version: "3.7"

services:
  backend:
    build:
      context: ./backend/typescript
      dockerfile: Dockerfile
    volumes:
      - ./backend/typescript:/app
      - /app/node_modules
    ports:
      - 5000:5000
    dns:
      - 8.8.8.8
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/typescript/.env

volumes:
  postgres_data:
