# `docker-compose up --build` (regular initialization)
# `docker-compose --profile firebase up --build` 

version: "3.7"

services:
  frontend:
    # TODO: rename container for your project
    container_name: scv2_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
  ts-backend:
    # TODO: rename container for your project
    container_name: scv2_ts_backend
    build:
      context: ./backend/typescript
      dockerfile: Dockerfile
    volumes:
      - ./backend/typescript:/app
      - /app/node_modules
    ports:
      - 8080:8080
    dns:
      - 8.8.8.8
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
  db:
    # TODO: rename container for your project
    container_name: scv2_db
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db-init:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB_DEV},${POSTGRES_DB_TEST}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  firebase-emulator:
    container_name: firebase_emulator
    build: 
      context: ./firebase
      dockerfile: Dockerfile
    ports:
      - 5003:5003  # Port for Firebase Emulator Suite UI
      - 9099:9099  # Port for Authentication Emulator
      - 5002:5002  # Port for Firestore Emulator (adjust if conflicts with your backend)
      - 9199:9199  # Port for Storage Emulator
      - 4500:4500 # Internal port for logging (firebase)
      - 4400:4400 # Internal port for hub (firebase)
    environment:
      - FIREBASE_TOKEN="1//05wAMTqkNDx8mCgYIARAAGAUSNwF-L9Ir1jSF3Fj3JvZEik_LuOC6_0MGPNj2mLrhiHaFc10AkmIHz5vxFhMIPoFMWvz4mtfPQv8"
    depends_on:
      - ts-backend  
    profiles:
      - firebase-emulator
    # healthcheck:
    #   test: ["curl", "--fail http://localhost:5003"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s

volumes:
  postgres_data: