"""Add Entity file storage file name

Revision ID: 797bfedc3a06
Revises: dedc5f7be10c
Create Date: 2021-08-16 04:55:26.406967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "797bfedc3a06"
down_revision = "dedc5f7be10c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entities", sa.Column("file_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entities", "file_name")
    # ### end Alembic commands ###
