"""Initial migration

Revision ID: dedc5f7be10c
Revises: 
Create Date: 2021-06-13 17:16:55.426036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dedc5f7be10c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("string_field", sa.String(), nullable=False),
        sa.Column("int_field", sa.Integer(), nullable=False),
        sa.Column(
            "enum_field", sa.Enum("A", "B", "C", "D", name="enum"), nullable=False
        ),
        sa.Column("string_array_field", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("bool_field", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("auth_id", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("User", "Admin", name="roles"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("entities")
    # ### end Alembic commands ###
