"""Add simple entity model

Revision ID: fd470c3ddd8a
Revises: 797bfedc3a06
Create Date: 2022-04-12 03:27:15.220305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd470c3ddd8a'
down_revision = '797bfedc3a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_field', sa.String(), nullable=False),
    sa.Column('int_field', sa.Integer(), nullable=False),
    sa.Column('enum_field', sa.Enum('A', 'B', 'C', 'D', name='simple_entity_enum'), nullable=False),
    sa.Column('string_array_field', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('bool_field', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simple_entities')
    # ### end Alembic commands ###
