name: "Code Analysis"

on:
  push:
    branches:
      - main
    paths-ignore:
      # Ignore files from third-party packages, e.g. Swagger
      - 'backend/python/app/static'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'backend/python/app/static'

  schedule:
    # Scheduled workflows run on the latest commit on the default or base branch.
    # The shortest interval you can run scheduled workflows is once every 15 minutes.
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: '0 0 * * 0'

jobs:
  codeql-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        # CodeQL supports the following languages: go, javascript, csharp, python, cpp, java.
        # Select javascript for typescript
        with:
          languages: javascript, python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
